controller_list:
  - name: fake_fr3_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - fr3_finger_joint1
  - name: fake_fr3_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
initial:  # Define initial robot poses per group
  - group: fr3_hand
    pose: hand_home
  - group: fr3_arm
    pose: home_pose