# # MoveIt-specific simulation settings
# moveit_sim_hw_interface:
#     joint_model_group: controllers_initial_group_
#     joint_model_group_pose: controllers_initial_pose_
# # Settings for ros_control control loop
# generic_hw_control_loop:
#     loop_hz: 300
#     cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#     joints:
#         - fr3_joint1
#         - fr3_joint2
#         - fr3_joint3
#         - fr3_joint4
#         - fr3_joint5
#         - fr3_joint6
#         - fr3_joint7
#         - fr3_finger_joint1
#     sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
fr3_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  gains:
    fr3_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
    fr3_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    fr3_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
    fr3_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
    fr3_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
    fr3_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    fr3_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

fr3_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - fr3_finger_joint1

    gains:
        fr3_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }

    state_publish_rate: 25

# controller_list:
#   - name: fr3_arm_controller
#     type: $(arg fake_execution_type)
#     joints:
#       - fr3_joint1
#       - fr3_joint2
#       - fr3_joint3
#       - fr3_joint4
#       - fr3_joint5
#       - fr3_joint6
#       - fr3_joint7
#   - name: fr3_hand_controller
#     type: $(arg fake_execution_type)
#     joints:
#       - fr3_finger_joint1
# initial:  # Define initial robot poses per group
#   - group: fr3_arm
#     pose: home_pose
#   - group: fr3_hand
#     pose: hand_home